# Use root/example as user/password credentials
# version: '3.1'

services:

  db:
    image: docker.io/library/mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    command:
      --bind-address=db
    ports:
      - 3306:3306

  adminer:
    image: docker.io/library/adminer
    restart: always
    ports:
      - 8080:8080

